package ec.edu.ups.vista;

import com.mxrck.autocompleter.TextAutoCompleter;
import ec.edu.ups.controlador.CasoJpaController;
import ec.edu.ups.controlador.PersonaJpaController;
import ec.edu.ups.controlador.ViviendaJpaController;
import ec.edu.ups.modelo.Banco;
import ec.edu.ups.modelo.Caso;
import ec.edu.ups.modelo.DatosSistemaAleman;
import ec.edu.ups.modelo.PDFReportes;
import ec.edu.ups.modelo.Persona;
import ec.edu.ups.modelo.Vivienda;
import ec.edu.ups.utils.Utils;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.persistence.EntityManagerFactory;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Paul Idrovo
 */
public class Principal extends javax.swing.JFrame {

    private TextAutoCompleter cedulasAutocompletarCliente;
    private TextAutoCompleter cedulasAutocompletarGaratnte;
    private PersonaJpaController controladorPersona;
    private ViviendaJpaController controladorVivienda;
    private CasoJpaController controladorCaso;
    private EntityManagerFactory em;
    private List<DatosSistemaAleman> listaCuotas;

    public Principal() {        
        initComponents();
        this.setLocationRelativeTo(null);
        em = Utils.getEntityManagerFactory();
        controladorPersona = new PersonaJpaController(em);
        controladorVivienda = new ViviendaJpaController(em);
        controladorCaso = new CasoJpaController(em);
        cargarCedulas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtFechaNacimiento = new javax.swing.JTextField();
        txtSueldo = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtApellidoG = new javax.swing.JTextField();
        txtDireccionG = new javax.swing.JTextField();
        txtNombreG = new javax.swing.JTextField();
        txtSueldo1 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtFechaNacimiento1 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        dtFechaInicio = new com.toedter.calendar.JDateChooser();
        dtFechaFinal = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtCedulaGarante = new javax.swing.JTextField();
        txtAvaluo = new javax.swing.JTextField();
        txtCedulaCliente = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        spnInteres = new javax.swing.JSpinner();
        spnCapital = new javax.swing.JSpinner();
        cmbVivienda = new javax.swing.JComboBox<>();
        btnGenerarPagos = new javax.swing.JButton();
        txtDireccionVivienda = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DATOS CLIENTE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        txtNombre.setEnabled(false);

        txtApellido.setEnabled(false);

        txtDireccion.setEnabled(false);

        jLabel9.setText("NOMBRE");

        jLabel10.setText("APELLIDO");

        jLabel11.setText("DIRECCION");

        jLabel12.setText("F. NACIMIENTO");

        jLabel18.setText("SUELDO");

        txtFechaNacimiento.setEnabled(false);

        txtSueldo.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(55, 55, 55)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDireccion)
                            .addComponent(txtApellido)
                            .addComponent(txtNombre)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(73, 73, 73)
                        .addComponent(txtSueldo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(35, 35, 35)
                        .addComponent(txtFechaNacimiento)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DATOS GARANTE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jLabel13.setText("F. NACIMIENTO");

        jLabel14.setText("DIRECCION");

        jLabel15.setText("NOMBRE");

        jLabel16.setText("APELLIDO");

        txtApellidoG.setEnabled(false);

        txtDireccionG.setEnabled(false);

        txtNombreG.setEnabled(false);

        txtSueldo1.setEnabled(false);

        jLabel19.setText("SUELDO");

        txtFechaNacimiento1.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGap(73, 73, 73)
                                .addComponent(txtSueldo1, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(35, 35, 35)
                                .addComponent(txtFechaNacimiento1)))
                        .addGap(0, 0, 0))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel14))
                        .addGap(55, 55, 55)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDireccionG)
                            .addComponent(txtApellidoG)
                            .addComponent(txtNombreG))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtNombreG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtApellidoG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtDireccionG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFechaNacimiento1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txtSueldo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DATOS PARA PRESTAMO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jLabel1.setText("CAPITAL:");

        jLabel2.setText("CLIENTE CI:");

        jLabel3.setText("PROPIEDA:");

        jLabel4.setText("AVALUO:");

        jLabel5.setText("GARANTE CI:");

        dtFechaInicio.setDateFormatString("dd-MM-yyyy");

        dtFechaFinal.setDateFormatString("dd-MM-yyyy");

        jLabel6.setText("FECHA INICIO");

        jLabel7.setText("FECHA FINAL");

        txtCedulaGarante.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCedulaGaranteKeyTyped(evt);
            }
        });

        txtAvaluo.setEditable(false);

        txtCedulaCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCedulaClienteKeyTyped(evt);
            }
        });

        jLabel8.setText("INTERES");

        spnInteres.setModel(new javax.swing.SpinnerNumberModel(8.99d, 8.99d, 16.99d, 0.01d));

        spnCapital.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, null, 0.01d));

        cmbVivienda.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cmbViviendaFocusLost(evt);
            }
        });

        btnGenerarPagos.setText("GENERAR PAGOS");
        btnGenerarPagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarPagosActionPerformed(evt);
            }
        });

        txtDireccionVivienda.setEditable(false);

        jLabel17.setText("DIRECCION:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dtFechaInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dtFechaFinal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCedulaGarante)
                            .addComponent(txtCedulaCliente)
                            .addComponent(txtAvaluo)
                            .addComponent(spnInteres)
                            .addComponent(spnCapital, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cmbVivienda, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtDireccionVivienda))))
                .addGap(10, 10, 10))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(btnGenerarPagos)
                .addGap(130, 130, 130))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(spnCapital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCedulaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbVivienda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtAvaluo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDireccionVivienda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(7, 7, 7)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCedulaGarante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(spnInteres)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dtFechaInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(36, 36, 36))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(dtFechaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnGenerarPagos)
                        .addGap(10, 10, 10))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCedulaClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCedulaClienteKeyTyped
        char validar = evt.getKeyChar();
        int asscii = (int) validar;
        if (!Character.isDigit(validar) && validar != '\n' && asscii != 8 && validar != '') {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "INGRESE SOLO NUMEROS", "ERROR DE DATOS", JOptionPane.WARNING_MESSAGE);
        }
        if (validar == '\n') {
            try {
                Persona persona = controladorPersona.findPersona(txtCedulaCliente.getText());
                txtNombre.setText(persona.getNombres());
                txtApellido.setText(persona.getApellidos());
                txtDireccion.setText(persona.getDireccion());
                txtFechaNacimiento.setText(persona.getFechaNacimiento().toString());
                txtSueldo.setText(persona.getSueldo() + "");
                cmbVivienda.removeAllItems();
                controladorVivienda.findViviendaEntities().stream().filter(vivienda -> (vivienda.getPersonaCedula().getCedula().equals(txtCedulaCliente.getText()))).forEachOrdered(vivienda -> {
                    cmbVivienda.addItem(vivienda.getCodigoCatastral() + "");
                });

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "PERSONA NO EXISTENTE", "AGREGAR PERSONA", JOptionPane.INFORMATION_MESSAGE);
                CrearPersona crearPersona = new CrearPersona(this);
                crearPersona.setVisible(true);
                this.setVisible(false);
            }
        }
    }//GEN-LAST:event_txtCedulaClienteKeyTyped

    private void btnGenerarPagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarPagosActionPerformed

        SimpleDateFormat formato = new SimpleDateFormat("dd-MM-yyyy");
        String fechaInicio = formato.format(dtFechaInicio.getDate());
        String fechaFinal = formato.format(dtFechaFinal.getDate());
        Date tiempo = null;
        Date tiempo2 = null;
        java.util.Date fechaActual = dtFechaInicio.getDate();
        try {
            tiempo = new SimpleDateFormat("dd-MM-yyyy").parse(fechaInicio);
            tiempo2 = new SimpleDateFormat("dd-MM-yyyy").parse(fechaFinal);
        } catch (ParseException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        double minutos = (tiempo2.getTime() - tiempo.getTime()) / 60000;
        int mes = (int) minutos / 43800;
        listaCuotas = new ArrayList<>();
        double interes = (double) spnInteres.getValue();
        interes = interes / 12;
        double amortizacion = (double) spnCapital.getValue() / mes;
        DatosSistemaAleman primera = new DatosSistemaAleman();
        primera.setNumeroCuota(1);
        primera.setCapital((double) spnCapital.getValue());
        primera.setAmortizacion(amortizacion);
        primera.cuotaCalcular(interes);
        boolean prestamo = true;
        if (Integer.parseInt(txtAvaluo.getText().replace(".", ",")) < (int) spnCapital.getValue()) {
            if (primera.getCouta() > Integer.parseInt(txtSueldo.getText())) {
                if (txtCedulaGarante.getText().equals("")) {
                    prestamo = false;
                }
            }
        }
        if (prestamo) {
            listaCuotas.add(primera);
            for (int i = 1; i < mes; i++) {
                DatosSistemaAleman datos = new DatosSistemaAleman();
                datos.setNumeroCuota(i + 1);
                datos.setCapital(listaCuotas.get(i - 1).getCapital() - amortizacion);
                datos.setAmortizacion(amortizacion);
                datos.cuotaCalcular(interes);
                listaCuotas.add(datos);
            }
            PDFReportes gen = new PDFReportes();
            gen.createPDF(new File("C:\\Programas Java\\UPS\\3ROCICLO\\Parqueadero\\Reportes\\REPORTE_VALORES.pdf"),
                    listaCuotas, spnCapital.getValue().toString(), spnInteres.getValue().toString(), mes);

            File objetofile = new File("C:\\Programas Java\\UPS\\3ROCICLO\\Parqueadero\\Reportes\\REPORTE_VALORES.pdf");
            try {
                Desktop.getDesktop().open(objetofile);
            } catch (IOException ex) {

            }

            int confirmado = JOptionPane.showConfirmDialog(null, "CONFIRMAR PRESTAMO");
            if (JOptionPane.OK_OPTION == confirmado) {
                Caso nuevoCaso = new Caso();
                nuevoCaso.setBancoId(new Banco(1));
                nuevoCaso.setFechaInicio(dtFechaInicio.getDate());
                nuevoCaso.setFechaFinal(dtFechaFinal.getDate());
                nuevoCaso.setCapital((double) spnCapital.getValue());
                nuevoCaso.setViviendaCodigoCatastral(new Vivienda((int) cmbVivienda.getSelectedItem()));
                nuevoCaso.setGaranteId(txtCedulaGarante.getText());
                nuevoCaso.setValorInteres((double) spnInteres.getValue());
                controladorCaso.create(new Caso(WIDTH, minutos, interes, tiempo, tiempo2));
            }
        }
    }//GEN-LAST:event_btnGenerarPagosActionPerformed

    private void cmbViviendaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmbViviendaFocusLost
        Vivienda vivienda = controladorVivienda.findVivienda(Integer.parseInt(cmbVivienda.getSelectedItem().toString()));
        txtDireccionVivienda.setText(vivienda.getDireccion());
        txtAvaluo.setText(vivienda.getAvaluo() + "");
    }//GEN-LAST:event_cmbViviendaFocusLost

    private void txtCedulaGaranteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCedulaGaranteKeyTyped
        char validar = evt.getKeyChar();
        int asscii = (int) validar;
        if (!Character.isDigit(validar) && validar != '\n' && asscii != 8 && validar != '') {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "INGRESE SOLO NUMEROS", "ERROR DE DATOS", JOptionPane.WARNING_MESSAGE);
        }
        if (validar == '\n') {
            try {
                Persona persona = controladorPersona.findPersona(txtCedulaGarante.getText());
                txtNombreG.setText(persona.getNombres());
                txtApellidoG.setText(persona.getApellidos());
                txtDireccionG.setText(persona.getDireccion());
                txtFechaNacimiento1.setText(persona.getFechaNacimiento().toString());
                txtSueldo1.setText(persona.getSueldo() + "");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "PERSONA NO EXISTENTE", "AGREGAR PERSONA", JOptionPane.INFORMATION_MESSAGE);
                CrearPersona crearPersona = new CrearPersona(this);
                crearPersona.setVisible(true);
                this.setVisible(false);
            }
        }
    }//GEN-LAST:event_txtCedulaGaranteKeyTyped

    public void cargarCedulas() {
        List<Persona> listp = controladorPersona.findPersonaEntities();
        cedulasAutocompletarCliente = new TextAutoCompleter(txtCedulaCliente);
        cedulasAutocompletarGaratnte = new TextAutoCompleter(txtCedulaGarante);
        listp.stream().map(persona -> {
            cedulasAutocompletarCliente.addItem(persona.getCedula());
            return persona;
        }).forEachOrdered(persona -> {
            cedulasAutocompletarGaratnte.addItem(persona.getCedula());
        });
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    UIManager.setLookAndFeel("com.jtattoo.plaf.hifi.HiFiLookAndFeel");
                    //UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                } catch (Exception e) {
                }
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerarPagos;
    private javax.swing.JComboBox<String> cmbVivienda;
    private com.toedter.calendar.JDateChooser dtFechaFinal;
    private com.toedter.calendar.JDateChooser dtFechaInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSpinner spnCapital;
    private javax.swing.JSpinner spnInteres;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtApellidoG;
    private javax.swing.JTextField txtAvaluo;
    private javax.swing.JTextField txtCedulaCliente;
    private javax.swing.JTextField txtCedulaGarante;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtDireccionG;
    private javax.swing.JTextField txtDireccionVivienda;
    private javax.swing.JTextField txtFechaNacimiento;
    private javax.swing.JTextField txtFechaNacimiento1;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombreG;
    private javax.swing.JTextField txtSueldo;
    private javax.swing.JTextField txtSueldo1;
    // End of variables declaration//GEN-END:variables
}
